@startuml

actor "End-user" as Enduser

[Hologram Mediator] as CA

rectangle "Hologram Wallet & Messenger" as App {
  [Hologram app] as MA
}


rectangle "UnicID Issuer DTS" {
    [2060 Service Agent] as VS
    database "2060 Data Store" as DS
    [2060 WebRTC Server] as WebRTC
    database Postgres as PS
    [UnicID Issuer Backend (**this project**)] as GAIA
    [Vision Services] as VISION
}

App <--> Enduser
MA --> VS
MA <-- CA
CA <-- VS
MA --> WebRTC
VISION <--> GAIA
VISION --> DS
VISION <--> WebRTC
WebRTC <--> GAIA
GAIA --> DS
VS <--> GAIA
VS <--> PS
PS <--> GAIA

@enduml
