@startuml

actor "End-user" as Enduser

[Hologram Mediator] as CA

rectangle "Hologram Wallet & Messenger" as App {
  [Hologram app] as MA
}


rectangle "Hologram Gov ID Issuer VS" {
    [VS Agent] as VS
    [WebRTC Server] as WebRTC
    database Postgres as PS
    [Hologram Gov ID Issuer App (**this repo**)] as GAIA
    [Vision Services] as VISION
}

Enduser <-> App
MA --> VS
MA <-- CA
CA <-- VS
MA --> WebRTC
VISION <--> GAIA
VISION <--> WebRTC
WebRTC <--> GAIA
VS <--> GAIA
VS <--> PS
PS <--> GAIA

@enduml