package io.unicid.registry.enums;

public enum CreateStep {
	CITIZEN_ID,
	FIRST_NAME, 
	LAST_NAME,
	AVATAR_NAME,
	AVATAR_PIC,
	BIRTH_DATE, 
	PLACE_OF_BIRTH, 
	MRZ,
	PENDING_CONFIRM,
	WANT_TO_CHANGE,
	NEED_TO_CHANGE,
	CHANGE_CITIZEN_ID, 
	CHANGE_FIRST_NAME, 
	CHANGE_LAST_NAME, 
	CHANGE_AVATAR_NAME,
	CHANGE_AVATAR_PIC,
	CHANGE_BIRTH_DATE, 
	CHANGE_PLACE_OF_BIRTH, 
	CHANGE_MRZ,
	CAPTURE,
	PASSWORD, 
	FACE_CAPTURE, 
	FACE_VERIFICATION,
	FINGERPRINT_CAPTURE, 
	FINGERPRINT_VERIFICATION,
	WEBRTC_CAPTURE, 
	WEBRTC_VERIFICATION,
	ISSUE
	
	
}
