package io.unicid.registry.enums;

public enum RestoreStep {
	KNOW_ID, INPUT_ID, 
	
	CITIZEN_ID,
	FIRSTNAME, LASTNAME, AVATARNAME, BIRTHDATE, PLACE_OF_BIRTH, MRZ, METHOD, PASSWORD, FACE_VERIFICATION, FINGERPRINT_VERIFICATION,WEBRTC_VERIFICATION, ISSUE, DONE
}
