apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
  - name: q
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
---
# Public ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: public-{{ .Values.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.name }}.{{ .Values.domain }}
      secretName: {{ .Values.name }}.{{ .Values.domain }}-cert
  rules:
    - host: {{ .Values.name }}.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                 name: {{ .Values.name }}
                 port:
                   number: {{ .Values.service.port }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
   name: {{ .Values.name }}
   namespace: {{ .Values.namespace }}
spec:
   serviceName: {{ .Values.name }}
   replicas: {{ .Values.replicas }}
   selector:
      matchLabels:
         app: {{ .Values.name }}
   template:
      metadata:
         labels:
            app: {{ .Values.name }}
      spec:
         containers:
         -  name: {{ .Values.name }}-backend-container
            image: "{{ .Values.images.backend.repository }}:{{ .Values.images.backend.tag }}"
            imagePullPolicy: Always
            env:
            - name: AGENT_PORT
              value: "{{ .Values.service.port }}"
            - name: SERVICE_AGENT_ADMIN_URL
              value: "{{ .Values.agent.url }}"
            - name: POSTGRES_HOST
              value: {{ .Values.database.host }}
            - name: POSTGRES_USER
              value: {{ .Values.database.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.database.pwd }}
            - name: VISION_URL
              value: "{{ .Values.backend.vision }}"
            - name: WEBRTC_SERVER_URL
              value: "{{ .Values.backend.webrtc }}"
            - name: PUBLIC_BASE_URL
              value: "https://{{ .Values.name }}.{{ .Values.domain }}"
            - name: ID_VERIFICATION_TIMEOUT_SECONDS
              value: "{{ .Values.backend.timeout }}"
            - name: LOG_LEVEL
              value: "{{ .Values.backend.logLevel }}"
            ports:
            -  containerPort: {{ .Values.service.port }}

