apiVersion: v2
name: hologram-gov-id-issuer-vs-chart
description: A Helm chart for deploying Hologram Government ID Verifiable Service
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: vs-agent-chart
    version: v1.3.1-dev.1
    repository: oci://registry-1.docker.io/io2060
    condition: vs-agent-chart.enabled
  - name: vision-service-chart
    version: v0.4.1
    repository: oci://registry-1.docker.io/io2060
    condition: vision-service-chart.enabled
  - name: webrtc-server-chart
    version: v1.1.0-dev.34
    repository: oci://registry-1.docker.io/io2060
    condition: webrtc-server-chart.enabled