apiVersion: v2
name: unic.id-issuer-dts
description: A Helm chart for deploying the unic.id issuer application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: vs-agent
    version: 150-9c181b78dba10dab2fd3aa7b2f8bbfec9a1430e2
    repository: oci://registry-1.docker.io/io2060
  - name: postgresql
    version: 13.2.19
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.4.2
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled