apiVersion: v2
name: verifiable-id-issuer-chart
description: A Helm chart for deploying the unic.id issuer application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: vs-agent-chart
    version: ~1.3.0-dev
    repository: oci://registry-1.docker.io/io2060
    condition: vs-agent-chart.enabled
  - name: vision-matcher-chart
    version: v1.1.5
    repository: oci://registry-1.docker.io/io2060
    condition: vision-matcher-chart.enabled
  - name: vision-service-chart
    version: v0.3.1
    repository: oci://registry-1.docker.io/io2060
    condition: vision-service-chart.enabled
  - name: webrtc-server-chart
    version: ~1.1.0-dev
    repository: oci://registry-1.docker.io/io2060
    condition: webrtc-server-chart.enabled