name: Continuous Integration

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, labeled]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout unic-id
        uses: actions/checkout@v4
      
      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Setup node v20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Build
        run: |
          yarn build

      - name: Check Format
        run: |
          yarn check-format

      - name: Check Types
        run: |
          yarn check-types

      - name: Validate Helm chart
        run: helm lint ./charts
