name: Continuous Integration

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, labeled]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    uses: 2060-io/devops/workflows_call/2060-linter/template.yml@main
    with:
      charts-dir: ./charts

