name: PR Check

on:
  pull_request:
    branches: [ main, dev ]

env:
    QUARKUS_CONTAINER_IMAGE_USERNAME: ${{ secrets.DOCKER_HUB_LOGIN }}
    QUARKUS_CONTAINER_IMAGE_PASSWORD: ${{ secrets.DOCKER_HUB_PWD }}

jobs:
  pr_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Clean and verify
        run: |
          # Skipping Docker image build for PR verification
          ./mvnw clean verify fmt:check -B -Dquarkus.container-image.build=false -Dquarkus.container-image.push=false -Djib.skip=true